In [32]:
# Growth Accounting

import numpy as np
import pandas as pd

pd.options.mode.chained_assignment = None

df = pd.read_csv('growth_accounting.csv')
df_1 = df.loc[(df['year'] >= 1960) & (df['year'] <= 2000)]
df_2 = df_1.loc[df_1['country'].isin(['Australia', 'Austria', 'Belgium', 'Germany', 'France', 'United Kingdom', 'United States'])]


df_2['GDP_per_worker'] = (df_2['cgdpe'] + df_2['cgdpo']) / df_2['pop']
df_2['capital_per_worker'] = df_2['cn'] / df_2['pop']

df_2['gy'] = df_2['GDP_per_worker'].pct_change(periods=1) * 100
df_2['gk'] = df_2['capital_per_worker'].pct_change(periods=1) * 100
df_2['gz'] = df_2['ctfp'].pct_change(periods=1) * 100
df_2['alpha'] = (df_2['gy'] - df_2['gz']) / df_2['gk']

df_3 = df_2[['country', 'year', 'gy', 'gz', 'gk', 'alpha']].copy()

df_3.loc[df_3['year'] == 1960, 'gy'] = 'NaN'
df_3.loc[df_3['year'] == 1960, 'gz'] = 'NaN'
df_3.loc[df_3['year'] == 1960, 'gk'] = 'NaN'
df_3.loc[df_3['year'] == 1960, 'alpha'] = 'NaN'

df_3.head(45)

       country  year         gy         gz        gk      alpha
554  Australia  1960        NaN        NaN       NaN        NaN
555  Australia  1961  -0.193162    3.44256  -1.10248    3.29775
556  Australia  1962    3.55984  -0.437139  0.958041    4.17203
557  Australia  1963    5.87968    2.76286  0.847431    3.67797
558  Australia  1964    2.66419    1.75855   2.21461   0.408938
559  Australia  1965  -0.745444   -3.25778   2.46517    1.01913
560  Australia  1966    4.95686   0.732597   2.57577       1.64
561  Australia  1967    2.54471   0.340008    2.4914   0.884926
562  Australia  1968    5.98994    1.89676    3.1194    1.31217
563  Australia  1969    5.23546    3.41223   4.45767   0.409009
564  Australia  1970    1.50373   -1.46545   2.71776    1.09251
565  Australia  1971    1.56275    0.40462   3.95732   0.292655
566  Australia  1972    2.18796   -1.01611   4.62395   0.692929
567  Australia  1973    3.24862   0.109751   4.21893   0.743996
568  Australia  1974   -4.36485   -1.42993   3.47665  -0.844182
569  Australia  1975   0.368726   -2.46145   2.33655    1.21126
570  Australia  1976    2.69478  -0.122574   1.56137    1.80441
571  Australia  1977 -0.0151563  -0.982504   3.98914   0.242496
572  Australia  1978    3.50092    1.60345   5.25922    0.36079
573  Australia  1979    2.22813   0.820102     4.566   0.308374
574  Australia  1980    2.84429    1.61253   4.00536   0.307528
575  Australia  1981    3.34178   0.147379   3.83265   0.833471
576  Australia  1982   -3.39461  -0.693178   1.92459   -1.40364
577  Australia  1983    4.30155    3.88567  -1.14698  -0.362592
578  Australia  1984    1.74221   -3.28256  0.746732    6.72901
579  Australia  1985    1.98815   -1.20301   1.03934    3.07038
580  Australia  1986   0.142141   -4.25997   2.57809    1.70751
581  Australia  1987    5.79562    3.41306   2.88633   0.825463
582  Australia  1988     4.8749   0.194973   3.45045    1.35633
583  Australia  1989     2.4372  -0.514084   3.17166   0.930517
584  Australia  1990   -2.20587   -2.34744   2.13304   0.066371
585  Australia  1991   -2.00397  -0.327018   1.89573  -0.884592
586  Australia  1992    4.02635    2.04107   2.96448   0.669688
587  Australia  1993    2.02183  -0.836461   5.60511   0.509943
588  Australia  1994    2.96395   -1.10658   6.11562   0.665596
589  Australia  1995    3.41359   0.479504   5.45993   0.537385
590  Australia  1996    3.66051    2.17281   3.00297   0.495407
591  Australia  1997    4.08049    1.43032    2.3376    1.13371
592  Australia  1998    2.89137  -0.345602   3.21536    1.00672
593  Australia  1999    4.39454    0.20736   3.51546    1.19108
594  Australia  2000    1.51578   0.514016  -1.03753   -0.96553
622    Austria  1960        NaN        NaN       NaN        NaN
623    Austria  1961    5.44791    5.41859   3.46809  0.0084552
624    Austria  1962    2.80127 -0.0547457   3.05208   0.935761
625    Austria  1963    3.44495    1.18511   2.18962    1.03207